Сетки страниц и крупных блоков
htmlacademy-htmlcss/1811947-sedona-33 pull request #4
Opened 2022-02-17 14:45 UTC by r33ha

Не совсем уверен в правильности разметки основной страницы каталога

2022-02-18 07:09 UTC, CCher requested changes

2022-02-18 07:09 UTC, CCher commented on index.html
> +      <img class="logo" src="images/vector.svg" alt="Добро пожаловать">
![image](https://user-images.githubusercontent.com/12691832/154628774-b1a28463-3e96-4247-abeb-e6a68b305d1a.png)
Я уже писал Вам про использование заглавных букв в названии файлов - это пример, что не нужно использовать заглавные буквы в названиях файлов.

2022-02-18 07:09 UTC, CCher commented on index.html
> +      </div>
если Вы решили использовать `section`, то нужно сделать им заголовок (иначе на защите засчитают ошибку), либо вместо `section` используйте `div`

2022-02-18 07:09 UTC, CCher commented on catalog.html
> +            </div>
этот тег ничего не закрывает. Проверьте.

2022-02-18 07:09 UTC, CCher commented on catalog.html
> +        </div>
на строках 209-213 получилась какая-то каша: 
1. В `ul` может вкладываться только `li`
2. `/select` не может закрываться после закрытия другого тега
3. `label` должен принадлежать какому-то тегу либо вкладыванием в тег, либо через `id=""` `for=""`
![image](https://user-images.githubusercontent.com/12691832/154634085-54b69fb3-9a18-4dd4-b3fb-a47dcb06d179.png)

2022-02-18 07:09 UTC, CCher commented on catalog.html
> +        </div>
и далее  `/section` закрывает `div` или просто не нужен, т.к. див и ниже ещё закрывается.

2022-02-18 07:10 UTC, CCher commented on catalog.html
> +        </div>
Необходимы исправления ошибок в структуре файла.

2022-02-27 12:51 UTC, r33ha commented
Появилось несколько вопросов.
1. Почему не отрабатывает margin-left у user menu
2. Как правильно сделать отступ у лого Седоны
3. И как правильно выровнить текст Найдено Гостиниц на странице каталога

2022-02-27 13:48 UTC, CCher approved these changes

2022-02-27 13:48 UTC, merged